### ISSUE TITLE
EFIPartitionForInstall

### ISSUE THREAD

**Issue by MilesWuCode** [sowson/hackintosh#1]
Hi
EFIPartitionForInstall/EFI add to my usb
first boot , can format and copy file to my ssd
second boot , can not see apfs
but
EFIPartition/EFI can see apfs

**Comment by sowson** [comment]
Can you elaborate a bit more? Where is the issue? The first time you boot you format by disk utility the drive and install on it right? And then you start from Macintosh HD and all works on booted OS you use for the "regular" EFI right? So what does not work...? I am confused.

**Comment by MilesWuCode** [comment]
sorry, my bad
driver -> ApfsDriverLoader.efi not working ,sometime...
rebuild usb driver, i can find my apfs ssd
